name: Deploy Vue + Vite to GitHub Pages

on:
  push:
    branches:
      - master   # ou a branch que você usa como principal

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: |
          cd teste-imigracao
          npm install

      - name: Build do projeto
        run: |
          cd teste-imigracao
          npm run build

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./teste-imigracao/dist